# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C36h9H0DXfkJlqAiJ82UYp2fWBZqThS8
"""

import pandas as pd

#df =pd.read_csv("pathname")
df =pd.read_csv("/main.csv")
df

df.to_csv("/filteredCountry.csv",index=False)

x=df.groupby('COUNTRY')
x.get_group('USA (CA)')

